name: Java Spring MVC CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонирование репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Установка JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Сборка проекта с Maven
      - name: Build the project
        run: mvn clean package

      # 4. Запуск модульных тестов
      - name: Run tests
        run: mvn test

      # 5. Сохранение артефакта сборки (JAR-файла)
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: spring-mvc-app
          path: target/*.jar
